Controllers/InputController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBasic.Extensions;
using MvcBasic.Models;

namespace MvcBasic.Controllers
{
    public class InputController : Controller
    {
        // GET: Input
        [HttpPost]
        [Button(ButtonName = "Search")]
        [ValidateAntiForgeryToken]
        public ActionResult Index()
        {
            Input hl = new Input();

            ViewBag.SelectList = new SelectListItem[] {
                new SelectListItem() { Value="001", Text="選択①" },
                new SelectListItem() { Value="002", Text="選択②" },
                new SelectListItem() { Value="003", Text="選択③" }
            };

            return View(hl);
            //return View();
        }

        //public ActionResult HelloView()
        //{
        //    Input hl = new Input();

        //    ViewBag.SelectList = new SelectListItem[] {
        //        new SelectListItem() { Value="001", Text="選択①" },
        //        new SelectListItem() { Value="002", Text="選択②" },
        //        new SelectListItem() { Value="003", Text="選択③" }
        //    };

        //    return View(hl);
        //}

        [HttpPost]
        public ActionResult HelloView(Input hl)
        {

            ViewBag.SelectList = new SelectListItem[] {
                new SelectListItem() { Value="001", Text="選択①" },
                new SelectListItem() { Value="002", Text="選択②" },
                new SelectListItem() { Value="003", Text="選択③" }
            };
            return View(hl);
        }
    }
}

Controllers/InputListController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcBasic.Extensions;
using MvcBasic.Models;

namespace MvcBasic.Controllers
{
    public class InputListController : Controller
    {
        public MvcBasicContext db = new MvcBasicContext();


        // GET: InputList
        [HttpPost]
        [Button(ButtonName = "ListBox")]
        [ValidateAntiForgeryToken]
        public ActionResult Index()
        {
            BaseModel member = new BaseModel();
            // これもOKだった
            //member.SelectedMember = new List<SelectListItem>()
            //{
            //    new SelectListItem() {Value = "1", Text = "日曜日" },
            //    new SelectListItem() {Value = "2", Text = "月曜日" },
            //    new SelectListItem() {Value = "3", Text = "火曜日" , Selected = true},
            //    new SelectListItem() {Value = "4", Text = "水曜日" },
            //    new SelectListItem() {Value = "5", Text = "木曜日" },
            //    new SelectListItem() {Value = "6", Text = "金曜日" },
            //    new SelectListItem() {Value = "7", Text = "土曜日" },
            //};

            // これはダメだったパターン
            // aには、Listははいった。
            //var selectMember = db.Members.OrderBy(b => b.Id);
            //var a = selectMember.ToList();

            // OK♪
            // DBから値を取得した。
            member.SelectedMember = db.Members.Select(s=> new SelectListItem
            { 
                Value = s.Id.ToString(),
                Text = s.Name,
            });

            return View(member);
        }
    }
}

Controllers/TableController.cs
using MvcBasic.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MvcBasic.Controllers
{
    public class TableController : Controller
    {
        public MvcBasicContext db = new MvcBasicContext();

        public IPagedList<Member> pagedList;

        // GET: Table
        //[Route("Table/Index/{id?}")]
        // 引数をidにしないといけない
        // ヒントはRouteConfig.csにある。ルーティング
        public ActionResult Index(int? id)
        {
            //var members = db.Database.SqlQuery<Member>("SELECT * FROM Members;");
            //var members = db.Members.Select(x => x);
            //return View(members);
            //

            // データベースから取得するためのIQueryable型を用意
            // OrderBy(b=>b.Id)はなぜか重要
            IQueryable<Member> members = db.Members.OrderBy(b=>b.Id);
                //.Where(b => b.)
                //.OrderBy(b => b.Title);

            int pageNumber = id?? 1; // ページ番号
            int pageSize = 2;  // ージに表示する件数

            //IPagedList<Member> memberPages = members.ToPagedList(pageNumber, pageSize); // Bookをページで取得

            // View(memberPages);
            pagedList = members.ToPagedList(pageNumber, pageSize);
            return View(pagedList);

            //return View(db.Members);

        }

        // GET: Members/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 をご覧ください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Email,Birth,Married,Memo")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(member);
        }

        /// <summary>
        /// BaseModelテーブルに追加できる
        /// </summary>
        private void BaseModelInsert()
        {
            /*
            db.BaseModel.Add(new BaseModel
            {
                
                Name = "追加",
                Email = "mail@mail",
                Birth = DateTime.Now,
                Married = true,
                Memo = "メモ",
                Status = 1,
            });
            db.SaveChanges();
            */
            /*
            (
                new BaseModel {
            
                }
            )
            .
            */
            (
                new List<BaseModel>()
                {
                    new BaseModel()
                    {
                        Name = "追加",
                        Email = "mail@mail",
                        Birth = DateTime.Now,
                        Married = true,
                        Memo = "メモ",
                        Status = 1,
                    },
                    new BaseModel()
                    {
                        Name = "追加2",
                        Email = "mail@mail",
                        Birth = DateTime.Now,
                        Married = false,
                        Memo = "メモ",
                        Status = 2,
                    },
                }
            )
            .Where(e => e.Status == 1)
            .Skip(2)
            .ToList()
            .ForEach(
                e =>
                {
                    db.BaseModel.Add(e);
                    db.SaveChanges();
                }
            );

        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email,Birth,Married,Memo")] Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Table/Create.cshtml
@model MvcBasic.Models.Member

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Married, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Married)
                    @Html.ValidationMessageFor(model => model.Married, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Memo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Memo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Memo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Table/Delete.cshtml
@model MvcBasic.Models.Member

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Married)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Married)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Memo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Memo)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Table/Details.cshtml
@model MvcBasic.Models.Member

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Married)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Married)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Memo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Memo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Table/Edit.cshtml
@model MvcBasic.Models.Member

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Married, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Married)
                    @Html.ValidationMessageFor(model => model.Married, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Memo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Memo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Memo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Table/Index.cshtml
@*@model IEnumerable<MvcBasic.Models.Member>*@
@using PagedList
@using PagedList.Mvc
@*@model PagedList.IPagedList<MvcBasic.Models.Member> // IPagedList型で渡す*@
@model PagedList.IPagedList<MvcBasic.Models.Member>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("正しい例：Go to ~/Input/Index/4", "Index", "Input")
</p>
@using (Html.BeginForm("Index", "Input"))
{
    @Html.AntiForgeryToken();

    // テキストボックス等の入力項目の設定

    <input type="submit" name="Search" value="複数のビュー機能へ">
    <input type="submit" name="Clear" value="クリア">
}
@using (Html.BeginForm("Index", "InputList"))
{
    @Html.AntiForgeryToken();

    // テキストボックス等の入力項目の設定

    <input type="submit" name="ListBox" value="リストボックスへ">
    <input type="submit" name="Clear" value="クリア">
}
<table class="table">
    <tr>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>誕生日</th>
        <th>既婚</th>
        <th>備考</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td id="name">@item.Name</td>
            <td id="email">@item.Email</td>
            <td>@item.Birth</td>
            <td>@item.Married</td>
            <td>@item.Memo</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>
// ページ番号表示
@*@Html.PagedListPager(Model, page => Url.Action("Index", page))*@
@*@Html.PagedListPager(Model, page => Url.Action("Index", "Table", page.ToString()))*@
@Html.PagedListPager(Model, page => Url.Action("Index", "Table", new { id = page }))

